global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  #  axum-prometheus exposes /metrics at port 8080
  - job_name: "axum-api"
    scrape_interval: 15s # Increased to give the CPU some breathing room
    scrape_timeout: 14s # Increased from the 10s default
    static_configs:
      - targets: ["axum-api:8080"]
    metrics_path: "/metrics"

  # System metrics from Node Exporter
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
