apiVersion: v1 # Tried for a custom Side Proxy as a subsitute for linkerd
kind: Service
metadata:
  name: spire-server
  namespace: spire
  labels:
    app: spire-server
spec:
  clusterIP: None
  selector:
    app: spire-server
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
