apiVersion: v1 # Tried for a custom Side Proxy as a subsitute for linkerd
kind: Namespace
metadata:
  name: spire
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: spire
spec:
  serviceName: spire-server
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server-sa
      containers:
        - name: spire-server
          image: ghcr.io/spiffe/spire-server:1.8.0
          args: ["-config", "/run/spire/config/spire-server.conf"]
          ports:
            - containerPort: 8081
              name: grpc
          volumeMounts:
            - name: spire-config
              mountPath: /run/spire/config
              readOnly: true
            - name: spire-data
              mountPath: /run/spire/data
      volumes:
        - name: spire-config
          configMap:
            name: spire-server-config
  volumeClaimTemplates:
    - metadata:
        name: spire-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server-config
  namespace: spire
data:
  spire-server.conf: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "parcel.local"
      data_dir = "/run/spire/data"
      log_level = "INFO"

      ca_key_type = "ec-p256"
      ca_ttl = "2160h"          # 90 days Master CA life
    }
    plugins {
    DataStore "sql" {
          plugin_data {
            database_type = "sqlite3"
            connection_string = "/run/spire/data/datastore.sqlite3"
          }
        }

        NodeAttestor "k8s_psat" {
          plugin_data {
            clusters = {
              "gke-cluster" = {
                service_account_allow_list = ["spire:spire-agent"]
              }
            }
          }
        }

        KeyManager "disk" {
          plugin_data {
            keys_path = "/run/spire/data/keys.json"
            key_type = "ec-p256"
        }
      }
    }
