apiVersion: v1
kind: Namespace
metadata:
  name: parcel-app

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: parcel-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  namespace: parcel-app
spec:
  clusterIP: None
  selector:
    app: redis-cluster
  ports:
    - port: 6379
      name: client
    - port: 16379
      name: gossip

---
apiVersion: v1
kind: Service
metadata:
  name: axum-api-service
  namespace: parcel-app
spec:
  selector:
    app: axum-api
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: parcel-app
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: parcel-app
spec:
  selector:
    app: grafana
  ports:
    - port: 3001
      targetPort: 3000
  type: NodePort
