apiVersion: v1
kind: Namespace
metadata:
  name: parcel-app

# POSTGRES

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: parcel-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
